# Generated by Django 4.1.7 on 2023-03-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialschoices',
            options={'verbose_name': 'materialschoice', 'verbose_name_plural': 'materialschoices'},
        ),
        migrations.AlterModelTable(
            name='materialschoices',
            table='submissions_materialschoices',
        ),
    ]
